### ISSUE TITLE
[Wish] Benutzer können nicht gelöscht werden

### ISSUE THREAD

**Issue by Jaren95** [timvallandi/flvw-checkin#10]
Anlegte Benutzer können weder vom Vorstand noch vom Benutzer selbst gelöscht werden.

**Comment by timvallandi** [comment]
Diese Funktion wird bald (vermutlich mit nächstem Release am 01.10.) verfügbar sein.

**Comment by timvallandi** [comment]
Benutzer können mittlerweile vom Vorstand gelöscht werden
