### ISSUE TITLE
Information zu Impfung oder Genesung hinterlegen

### ISSUE THREAD

**Issue by Philip-Albrecht** [timvallandi/flvw-checkin#100]
Eine Möglichkeit Informationen zu hinterlegen, ob ein Teilnehmer bereits geimpft ist oder als genesen gilt, wäre super! Oder auch bzgl Tests.

Dazu habe ich in der Mail vom Verband etwas gelesen, gibt's dazu schon konkrete Infos?

**Comment by timvallandi** [comment]
Diese Funktion wird zeitnah umgesetzt

**Comment by timvallandi** [comment]
Mit Update auf Verson 3.5 wurde dieses Feature umgesetzt.
