### ISSUE TITLE
Anwesenheitsliste generieren - Suchbegriff wird ignoriert

### ISSUE THREAD

**Issue by ThomasSchreiber22** [timvallandi/flvw-checkin#103]
Die Funktion "Anwesenheitslisten" soll eine Anwesenheitsliste für eine bestimmte Person generieren. Allerdings werden die eingegebenen Suchbegriffe (Vorname und Nachname) ignoriert und eine Liste über alle Personen erstellt. Das entspricht nicht dem erwarteten Ergebnis

**Comment by timvallandi** [comment]
Es wird eine Anwesenheitsliste (bzw. mehrere Anwesenheitslisten) mit allen Zeiträumen, in denen die gesuchte Person anwesend war, generiert. Und in dieser Liste tauchen dann alle Personen mit denen die Person in den entsprechenden Zeiträumen auf dem Sportgelände in Kontakt gekommen sein könnte.
