### ISSUE TITLE
Voranmeldung und CheckIn bei Wettkampf-Veranstaltungen

### ISSUE THREAD

**Issue by NGoevert** [timvallandi/flvw-checkin#104]
Hallo Tim,

bei der Durchführung von inzwischen zwei Wettkampfveranstaltungen (Leichtathletik) haben wir folgende Erfahrung gemacht:

- Den Teilnehmenden haben wir im Vorfeld den Link für Athleten zugeschickt mit der Bitte, eine Voranmeldung durchzuführen, damit das CheckIn beim Betreten der Wettkampfstätte möglichst schnell erfolgen kann.
- Alle diejenigen, die davon Gebrauch gemacht haben, hatten beim CheckIn über den durch den FLVW-CheckIn verschickten Link das Problem, dass die Anmeldung vor Ort nicht erfolgreich war. Es passierte nichts, außer dass sich der Donut auf dem Screen drehte.
- Alle mussten ein zweites Mal auf den Link tippen, damit der dann folgende Klick auf CheckIn zum grünen Bildschirm führte.
- Wollte man sich auf diesem Screen wieder abmelden ("Check out"), wurde zwar faktisch eine Abmeldung generiert; allerdings war das einzige Feedback auf dem Screen wieder der sich unendlich drehende Donut.

Das Problem bestand unabhängig von der Plattform. Ich habe es auch nachstellen können (Anlegen einer Test-Veranstaltung, Voranmeldung und dann CheckIn-Versuch am Tag der Anmeldung). Getestet habe ich mit Firefox auf Android und auf Windows.

Weitere Hinweise:

- Die Nutzerführung ist für die Anwender nicht eindeutig: Viele haben nicht verstanden, dass eine Voranmeldung noch kein CheckIn ist und dass man den Link aus der E-Mail auf dem Smartphone benötigt, um sich vor Ort anzumelden.
- Stattdessen haben sich viele, die bereits vorangemeldet waren, über den ausgehängten QR-Code erneut angemeldet und mussten dann natürlich erneut die Adressdaten eingeben.
- Nach Abschluss der Voranmeldung erscheint auf dem Folgescreen eine Meldung, die sinngemäß lautet: "Anmeldung erfolgreich". Gut wäre, wenn hier explizit gemacht würde, dass es sich erst um die Voranmeldung handelt und dass man bitte den Link aus der E-Mail am Veranstaltungsort nutzen möge, um sich "echt" anzumelden.
- Verwirrung entstand auch darüber, dass eine Voranmeldung am Veranstaltungstag nicht mehr möglich ist, sondern dass man sofort registriert ist. Vor dem Hintergrund, dass alle Erklärungen zum Verfahren im Vorfeld gerne ignoriert werden, fällt mir leider kein guter Weg ein, diese Verwirrung zu verhindern.

Vielleicht lassen sich die oben geschilderten Probleme beheben und die weiter unten aufgeführten Fragen bezüglich der Ergonomie ja noch mildern. Vielen Dank schon jetzt für deine Bemühungen.

Viele Grüße
Norbert

**Comment by timvallandi** [comment]
Hallo Norbert, es gab ein Update für das Wettkampfmodul. 
Die Fehler müssten nun behoben sein.

**Comment by NGoevert** [comment]
Das CheckIn funktionniert nun mit dem Link aus der Voranmeldungs-E-Mail. Vielen Dank!
