### ISSUE TITLE
 Anlegen von geografisch auseinanderliegenden Platzanlagen

### ISSUE THREAD

**Issue by MaikOtto** [timvallandi/flvw-checkin#11]
Wo soll das passieren.

**Comment by timvallandi** [comment]
Die Funktion ist derzeit noch nicht vorhanden und wird in den nächsten Wochen verfügbar sein.

Geplant ist es etwa so (Ich will es aber noch nicht garantieren, dass es genau so funktionieren wird):

- Vorstand kann Platzanlagen anlegen im Bereich "Verein"

- Wenn eine neue Veranstaltung angelegt wird und mehrere Platzanlagen existieren, dann ist bei der Erstellung ein zusätzliches Attribut "Platz" einzugeben. 


- In der Zuschauer-Ansicht wird es dann möglich sein, vor der Auswahl der Veranstaltung eine Platzanlage auszuwählen.

**Comment by timvallandi** [comment]
Funktion wurde mit Update vom 20.10. umgesetzt
