### ISSUE TITLE
Veranstaltung erstellen - Auswärtsspiel

### ISSUE THREAD

**Issue by BertiRe** [timvallandi/flvw-checkin#111]
Hallo Tim,

ist es nicht sinnvoller, beim Hinzufügen einer Veranstaltung "Auswärtsspiel" das Auswahlfeld Sportstätte durch ein einfaches Schriftfeld (zum eintragen der gegnerischen Sportstätte) zu ersetzen?

So wie es derzeit ist, muss die Sportstätte des Heimvereins vorher als "Neue Sportstätte" durch einen Vereinsbenutzer "Vorstand" angelegt werden. Das wären im Laufe einer Saison so ziemlich viele Sportstätten und macht in meinen Augen wenig Sinn. Ein Trainer sollte die gegnerische Sportstätte auch so eintragen können.

Desweiteren sollte das Feld "Gastmannschaft" in Heimmannschaft oder gastgebende Mannschaft umbenannt werden. Gastmannschaft ist in dem Fall bei einem Auswärtsspiel die eigene Mannschaft.

Viele Grüße

**Comment by timvallandi** [comment]
Danke für den Hinweis! 
Die Änderungen wurden umgesetzt.
