### ISSUE TITLE
Kontaktdaten jedesmal neu eingeben

### ISSUE THREAD

**Issue by AndreOlbing** [timvallandi/flvw-checkin#12]
Bei jedem neuen login sind meine Kontaktdaten verschwunden, obwohl die App die beim letzten Mal erfolgreich gespeichert hat.

**Comment by timvallandi** [comment]
Handelt es sich dabei um einen Zuschauer-, Trainer- oder Vorstandsaccount?

**Comment by Philip-Albrecht** [comment]
Das Problem habe ich auch. Bei mir ist es ein Trainer-Account.

**Comment by timvallandi** [comment]
Im Trainer Account konnte ich den Fehler reproduzieren. 
Ich arbeite auch gerade schon an einer Lösung und werde es so schnell wie möglich aktualisieren

**Comment by timvallandi** [comment]
Update erfolgt. Fehler sollte behoben sein.

**Comment by Philip-Albrecht** [comment]
Funktioniert bei mir leider noch nicht. @timvallandi

**Comment by timvallandi** [comment]
Bitte einmal den Cache löschen ... evtl. hat der Browser noch etwas von der alten Version zwischengespeichert.

**Comment by Philip-Albrecht** [comment]
Leider auch nicht die Lösung. Sogar mit zwei Browsern (Safari und Chrome) versucht

**Comment by Philip-Albrecht** [comment]
Funktioniert jetzt!👍🏼
