### ISSUE TITLE
Regeltermine erstellen

### ISSUE THREAD

**Issue by Philip-Albrecht** [timvallandi/flvw-checkin#13]
z.B. Training jeden Dienstag und Donnerstag

**Comment by timvallandi** [comment]
Wird in einem der nächsten Releases berücksichtigt

**Comment by timvallandi** [comment]
Funktion wurde bei heutigem Release berücksichtigt.

Die Funktion ist nur für die Veranstaltungsart "Training" verfügbar.

**Comment by Tho-Gra** [comment]
Nun habe ich ein Regeltermin erstellt, und habe mich verklickt.
Mittwochs sind sozusagen die Uhrzeiten falsch... 
Jetzt muss ich über 50 Termine löschen... 
Das löschen von Terminen ist seeeehr umständlich :)

Ein einfacheres "Sammellöschen"/Sammelauswahl wäre wünschenswert.
