### ISSUE TITLE
[Bug] check-out nicht möglich

### ISSUE THREAD

**Issue by Jaren95** [timvallandi/flvw-checkin#14]
Habe mich als Zuschauer für andere Veranstaltung bei meinem Verein registriert da ich Spielübergreifend da bin. Check-out Button reagiert nicht, und schmeißt mich nicht raus. Habe mich dann über meinen Vorstandsaccount als Zuschauer entfernt und werde bei Meine aktiven CheckIns auf anwesend angezeigt

**Comment by timvallandi** [comment]
Danke für den Hinweis. 
Ein Update wird so schnell wie möglich erfolgen.

**Comment by timvallandi** [comment]
Update erfolgt. Fehler sollte behoben sein.

**Comment by Jaren95** [comment]
Leider funktioniert es bei mir immernoch nicht.

**Comment by timvallandi** [comment]
Bitte nochmal probieren. Ggf. mal das Fenster / den Browser komplett schließen oder Cache leeren.
