### ISSUE TITLE
[wish] Schnittstelle zum DFBnet

### ISSUE THREAD

**Issue by Philip-Albrecht** [timvallandi/flvw-checkin#16]
Damit Spiele automatisch als Veranstaltungen übernommen werden

**Comment by timvallandi** [comment]
Das wäre wirklich optimal. Die Umsetzung dieser Funktion wird aber wahrscheinlich noch eine ganze Zeit dauern.
Da muss zunächst einmal beim DFB angefragt und eine Schnittstelle bereitgestellt werden

**Comment by 1Parri1** [comment]
Ich hatte vor ein Paar Tagen ein Gespräch mit einem APP Hersteller für Vereins apps, die nutzen laut deren aussage eine Schnittstelle von Fussball.de. Die Daten werden Täglich Aktualisiert. 

Vllt lässt sich da was machen, wenn man die Verbands Karte ausspielt? ;)

**Comment by timvallandi** [comment]
Wird in der nächsten Zeit leider nicht umgesetzt werden können.
