### ISSUE TITLE
Teammitglieder per CSV Import anlegen

### ISSUE THREAD

**Issue by ottopatrick** [timvallandi/flvw-checkin#17]
Viele Vereine im Verband nutzen DFBnet Verein. Dort habe ich die Möglichkeit die Teammitglieder mit Adresse und allen Informationen als CSV zu exportieren. Es wäre schön wenn man in der Übersicht des Teams das CSV direkt importieren könnte.

![image](https://user-images.githubusercontent.com/459261/94340569-2b857300-0003-11eb-9b02-460741f29b85.png)

**Comment by timvallandi** [comment]
Sehr gute Idee!
Nehme ich mit in die Liste auf und wird bald umgesetzt

**Comment by timvallandi** [comment]
Wäre super wenn du mir eine Beispiel-Datei an info@timvallandi.de zusenden könntest

**Comment by ottopatrick** [comment]
Habe ich dir geschickt.

**Comment by Tho-Gra** [comment]
Guten Tag, 
Wann wird dies ungefähr umgesetzt sein?!
Ich frage mit dem Hintergrund, ob ich mir noch die Mühe mache alles händisch einzutragen oder ob ich noch warte.

**Comment by timvallandi** [comment]
Funktion wurde mit heutigem Update hinzugefügt.
