### ISSUE TITLE
Mobile Registrierung kommt nicht zum Abschluss

### ISSUE THREAD

**Issue by Michel12345** [timvallandi/flvw-checkin#18]
Das Scannen des QR-Codes und eintragen der persönlichen Daten sowie die Auswahl der
Veranstaltung funktioniert einwandfrei.
Doch wenn man auf CheckIn geht läd es trotz bester Internetverbindung unendlich und die
Registrierung kommt nicht zum Abschluss.

**Comment by timvallandi** [comment]
Ohje ... dass das noch nicht eher einem aufgefallen ist. 

Wird heute noch behoben dieser Fehler!

**Comment by timvallandi** [comment]
Fehler beseitigt. Update ist raus. 

Jetzt sollte alles normal funktionieren. 

Sicherheitshalber einmal den Cache löschen vorm testen.

**Comment by Niko062** [comment]
@timvallandi ich habe diesen Fehler seit mehreren Tagen. Auf meinem Samsung S10 sehe ich beim "CheckIn" nur den roten Ladebalken und der läuft unerbittlich durch. Ich habe mehrere Browser genutzt und auch jeweils den Cache geleert. Keine Besserung. Ich habe auch mehrere Accounts genutzt. Meinen Vereinsadministrator-Account und einen extra Zuschauer-Account. In der Veranstaltung werde ich dann allerdings als "eingeloggt" angezeigt. Einige Zuschauer hatten das Problem beim letzten Spiel auch.

Was kann ich tun?

Vielen Dank in Voraus!

Gruß

Niko

**Comment by timvallandi** [comment]
Hallo Niko,

Kannst du mir sagen bei welchen Verein du es versuchst ? Dann schaue ich mir das ganze mal an.
Am 12. Aug. 2021, 09:41 +0200 schrieb Niko062 ***@***.***>:

**Comment by Niko062** [comment]
> Hallo Niko, Kannst du mir sagen bei welchen Verein du es versuchst ? Dann schaue ich mir das ganze mal an. Am 12. Aug. 2021, 09:41 +0200 schrieb Niko062 ***@***.***>:
> […](#)
> @timvallandi ich habe diesen Fehler seit mehreren Tagen. Auf meinem Samsung S10 sehe ich beim "CheckIn" nur den roten Ladebalken und der läuft unerbittlich durch. Ich habe mehrere Browser genutzt und auch jeweils den Cache geleert. Keine Besserung. Ich habe auch mehrere Accounts genutzt. Meinen Vereinsadministrator-Account und einen extra Zuschauer-Account. In der Veranstaltung werde ich dann allerdings als "eingeloggt" angezeigt. Einige Zuschauer hatten das Problem beim letzten Spiel auch. Was kann ich tun? Vielen Dank in Voraus! Gruß Niko — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi Tim,

na, klar.

Der Verein ist SC HERTEN 1932/87 .

Danke!

**Comment by timvallandi** [comment]
Alles klar danke!
Konnte einen Fehler finden und habe gerade einen kleinen Bugfix eingespielt. Der Fehler sollte wahrscheinlich in den nächsten Minuten dann behoben sein.
Am 12. Aug. 2021, 10:16 +0200 schrieb Niko062 ***@***.***>:
