### ISSUE TITLE
Trainer mehreren Teams zuordnen

### ISSUE THREAD

**Issue by BertiRe** [timvallandi/flvw-checkin#19]
Ein Trainer sollte mehreren Teams / Mannschaften zuordenbar sein. Gerade im Jugendbereich ist oft der Fall, dass ein Trainer mehrere Teams betreut.

**Comment by timvallandi** [comment]
Ist schon geplant diese Funktion.

Als Workaround bis dahin würde ich empfehlen, dass man einfach einen Vorstands-Account anlegt. Sobald die Funktion verfügbar ist, kann der Account in einen Trainer-Account geändert werden und die entsprechenden Mannschaften zugewiesen werden.

**Comment by Dirk-1971** [comment]
Hallo timvallandi,
was für einen Jahres-Account meinst du nun? Also wir haben auch das Problem - gerade im Jugendbereich - das ein Trainer mehrere Jugendmannschaften betreut. Es muss einfach die Möglichkeit eingeräumt werden einem Trainer auch mehr als nur eine Mannschaft zuzuordnen.

**Comment by timvallandi** [comment]
Euer Vorstand / Administrator, der euren Account erstellt hat, kann weitere Vorstand-Accounts anlegen, die dann Zugriff auf alle Mannschaften im Verein haben. 

Damit wäre zumindest temporär eine Lösung geschaffen. 

Man kann dann im Anschluss noch die Rolle (Derzeit "Trainer" oder "Vorstand") wieder ändern, sodass dann der Zugriff wieder weiter eingeschränkt wird und dann auch mehr als nur 1 Mannschaft zugewiesen werden kann.

**Comment by timvallandi** [comment]
Ab heute können den Trainern auch mehrere Mannschaften zugewiesen werden
