### ISSUE TITLE
Teams und Veranstaltungen zu löschen

### ISSUE THREAD

**Issue by Dirk-1971** [timvallandi/flvw-checkin#20]
Ich habe zum testen mal ein Team "Prüfung" und ein Testspiel angelegt. Leider kann man dieses nicht mehr löschen.
Kann man hierfür noch eine Löschfunktion einfügen? Es können ja auch geplante Spiele mal abgesetzt werden, dann müsste man diese Spiele doch auch löschen können.

**Comment by timvallandi** [comment]
Ja ist bereits in Planung/Entwicklung. 

Wird im Laufe der nächsten Woche freigeschaltet. 

Nach außen hin sind diese Teams aber auch erstmal nicht sichtbar, sodass du sie bis dahin zunächst einmal liegen lassen kannst und es keine weiteren Auswirkungen hat.

**Comment by Dirk-1971** [comment]
Danke! :)
