### ISSUE TITLE
Automatisches Ausloggen

### ISSUE THREAD

**Issue by Dirk-1971** [timvallandi/flvw-checkin#21]
In der Anleitung steht folgendes: _Sollte der Check-Out vergessen
werden, wird die Person nach einem vom Verein festgelegten Zeitraum automatisch ausgeloggt.
Die Anwesenheit wird gleichzeitig in der jeweiligen Veranstaltung getrackt, sodass die Vereinsmitglieder
(Trainer, Vorstand, Kassierer) zu jedem Zeitpunkt nachvollziehen können, wie viele Personen sich gerade
auf der Platzanlage befinden. Zudem können bei geografisch auseinanderliegenden Plätzen zukünftig
die verschiedenen Orte mit anderem QR-Code angegeben werden._

Wo lege ich als Verein den Zeitraum fest, nachdem jemand automatisch ausgeloggt wird?
Oder ist damit die Endzeit einer sportlichen Veranstaltung gemeint?

Das fände ich dann problematisch, da die Heimspiele unserer 2. und 1. Mannschaft immer am selben Tag stattfinden! Unsere 2. beginnt Ihr Heimspiel um 11:00 Uhr und unsere 1. Mannschaft später um 15:00 Uhr. Wenn sich dann Zuschauer oder auch Spieler beide Spiele ansehen, aber bereits nach dem Ende des Spiels von der 2. Mannschaft automatisch ausgeloggt werden, wäre dies nicht okay. Für das automatische ausloggen müsste es eine andere Zeiteinstellung geben.

Weiterhin kann ich die Rolle "Kassierer" nicht finden. Sollen die Kassierer auch einen Zugang erhalten und damit die Zuschauereinnahmen überprüfen? Ist dieses dann mit dem Datenschutz vereinbar und geprüft worden?

Geografisch auseinanderliegende Plätze sollen ja zukünftig mit anderem QR-Code angegeben werden. Ist den nun der QR-Code von jeder Veranstaltung anders? Dann müssten wir bei Heimspielen (wie oben schon geschrieben) bei unserer 1. und 2. Mannschaft 2 Plakate mit QR-Code aushängen. Dies wäre mit Sicherheit verwirrend.

**Comment by timvallandi** [comment]
Mit dem automatischen Check-Out ist die festgelegte Endzeit der Veranstaltung gemeint.

Für die Problematik mit der 1. und 2. Mannschaft gibt es dann derzeit folgende Lösungen:

1) Man muss sich als Zuschauer dann noch einmal für die 1. Mannschaft registrieren, sodass man bei beiden Spielen erfasst ist.

2) Man registriert sich als Zuschauer für eine "andere Veranstaltung" und gibt dort seinen Zeitraum selbst an, wo man auf dem Sportplatz anwesend ist. Man kann dort als Zuschauer einen Zeitraum von 15 Minuten bis 12 Stunden festlegen und bei Bedarf diese Anwesenheit auch verlängern.


Bei angelegten Veranstaltungen wird dann auch noch einmal diese Funktion ergänzt werden, sodass man die Anwesenheit bei Bedarf auch verlängern kann. 

------------------------------------


Die Rolle "Kassierer" existiert derzeit noch gar nicht und ist auch bisher nicht geplant. Wir möchten über diese App zunächst einmal auch keine Zuschauereinnahmen etc. erfassen, sondern uns zunächst einmal nur auf die Erfassung der Personen während der Pandemie beschränken. 

------------------------------------

Der QR-Code/Link ist ja derzeit an den Verein mit einem Platz bzw. Gelände gebunden (zum Beispiel flvw.app/fc-musterstadt).
Wenn dann in Zukunft das Hinzufügen mehrerer Standorte möglich ist, kann dann für jeden Standort ein weiterer QR-Code/Link erstellt werden (zum Beispiel flvw.app/fc-musterstadt-standort-b). Alle Veranstaltungen die an Standort A stattfinden werden dann über den Link des ersten QR-Codes zum Check-In zur Verfügung stehen und alle Veranstaltungen des Standortes B stehen dann über zweiten Link zur Verfügung.
