### ISSUE TITLE
Login für Familien

### ISSUE THREAD

**Issue by Timo-1981** [timvallandi/flvw-checkin#22]
Wie ist der Login für Familien mit Kindern gedacht? Wünschenswert wäre eine Funktion, wo man Familienangehörige hinzufügen kann. Oder habe ich da was übersehen?

**Comment by timvallandi** [comment]
Funktion ist in Planung.

Man kann bei einem Check-In dann noch einen "Familien-Button" auswählen, wo man die Familienmitglieder angeben kann, die eine Veranstaltung zusammen besuchen.

**Comment by Timo-1981** [comment]
Sehr gut.. weiter so
