### ISSUE TITLE
[Bug] falscher Login

### ISSUE THREAD

**Issue by Jaren95** [timvallandi/flvw-checkin#23]
Wenn sich ein anderer Vorstandsaccount sich mit dem QR-Code als zuschauer, mit seinen Daten, anmeldet wird der Account des Erstellers angezeigt und auf Anwesend gesetzt.
Die Account Daten vom Ersteller wurden schon 2x überschrieben mit Trainerdaten, sprich Name, Adresse & Tel.
Wenn ich mich also mit dem Account als Zuschauer anmelde werden also die falschen Daten als anwesend angezeigt.

**Comment by timvallandi** [comment]
Danke für den Hinweis. 
Wird geprüft und zeitnah korrigiert.

**Comment by Matzel92** [comment]
Ich habe dieses Problem ebenfalls.

**Comment by timvallandi** [comment]
Problem wurde mit heutigem Release gelöst
