### ISSUE TITLE
Vereinsbenutzer anlegen! Wie bekommt der Nutzer Ihr Passwort?

### ISSUE THREAD

**Issue by Dirk-1971** [timvallandi/flvw-checkin#25]
Hallo!

Ich habe in der APP nun Vereinsbenutzer angelegt mit deren Vereinsmail-Adressen. Kann es sein, dass die Nutzer keine Mail mit den Einloggdaten bekommt? Muss ich hierfür dann einen Screenshout erstellen und das Passwort noch manuell versenden?

Bei einem Vereinskollegen habe ich nun das Passwort zurückgesetzt, aber er hat weiterhin keine Mail von der APP bekommen.
Wie komme ich dann an die Passwörter ran?

**Comment by timvallandi** [comment]
Nach der Registrierung werden derzeit leider noch keine E-Mails verschickt. Diese Funktion wird bald ergänzt. 

Bei dem Problem mit dem Zurücksetzen des Passwortes bitte einmal die E-Mail Adresse prüfen ob sie korrekt ist und der Empfänger soll noch einmal bitte Spam-Ordner nachschauen. Wenn die Anwendung eine Erfolgsmeldung anzeigt (E-Mail mit Link verschickt), dann wurde auch eine Mail versendet.
