### ISSUE TITLE
Verwirrende Wortwahl!

### ISSUE THREAD

**Issue by Dirk-1971** [timvallandi/flvw-checkin#26]
Bitte auch mal die Wortwahl bei den Buttons anpassen! Oder wollte hier jemand Witze machen?
**VERWIRKLICHUNG**? Damit ist wohl **NEUER TERMIN** gemeint.
**VERLIEBT**? Damit ist wohl **VERGANGENHEIT** gemeint.
**LEIDEN**? Damit ist wohl **ANLEGEN** gemeint.
Hört sich beim Anlegen eines neuen **TEAMS** komisch an, wenn dort steht **TEAM MUSS…….LEIDEN!** :) 

![image](https://user-images.githubusercontent.com/71945909/94374494-e5b4d180-010c-11eb-96d9-a7d588855f02.png)

![image](https://user-images.githubusercontent.com/71945909/94374621-cc605500-010d-11eb-8080-3d36fdecb4a3.png)

![image](https://user-images.githubusercontent.com/71945909/94374667-0e899680-010e-11eb-9ae2-ede5ca824b2b.png)

**Comment by timvallandi** [comment]
Was ist da denn schief gelaufen? 
Das scheint mir manipuliert auszusehen ... So eine Wortwahl haben wir da niemals verwendet und in meinen Ansichten (auf verschiedenen Geräten) kann ich diese Worte auch nicht finden... geschweige denn im Source Code.

**Comment by Dirk-1971** [comment]
Kann das am Browser liegen? Eigentlich nutze ich Google Chrome. Ich habe die APP nun im Browser Edge von Windwos aufgerufen und da ist wirklich alles OK. :)

**Comment by timvallandi** [comment]
Ja das kann sein ... wobei ich es halt auch soeben mit Chrome getestet habe. Evtl mal den Cache löschen bei Google Chrome ?
