### ISSUE TITLE
[wish] Schiedsrichter

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#27]
Bisher ist es so geregelt, das der Schiedsrichter sich auf die Anwesenheitsliste des Heimvereins einträgt, und so wurde es auch vom FLVW / Schiedsrichterbelehrung angewiesen.

Wie genau ist es jetzt mit der Online Version zu handhaben? 
Schiedsrichter haben einen eigenen Login und können sich übergeordnet einer Mannschaft/Spiel zuweisen? muss das vom Heimverein eingepflegt werden?
Bisher habe ich keine Info dazu zur Online Version gefunden.

**Comment by timvallandi** [comment]
Ein extra Schiedsrichter-Login wird realisiert. Derzeit können Schiedsrichter nur über die Zuschauer-Funktion erfasst werden

**Comment by 1Parri1** [comment]
in der Anwesenheitsliste wird der Schiedsrichter als Zuschauer angezeigt.

Wäre es möglich das der Schiedsrichter unter den Spielern angezeigt wird, mit dem Zusatz darunter Schiedsrichter?

Das Gleiche gilt für die PDF Anwesenheitsliste.

**Comment by timvallandi** [comment]
Guter Hinweis. Das macht auf jeden Fall Sinn den Schiedsrichter in die Liste der Sportler aufzunehmen.
