### ISSUE TITLE
Problem mit mobilen Anmeldeformular

### ISSUE THREAD

**Issue by jh-new** [timvallandi/flvw-checkin#28]
Nach dem einscannen des QR-Code wir die Erfassungsseite gesatartet, aber das mobile Anmeldeformular baut sich nicht auf und die Zuschauer können sich nicht registrieren. Die Web-Seite bleibt leer, nach einiger Zeit kommt die Meldung die Seite lässt sich nicht öffnen.

**Comment by timvallandi** [comment]
Bitte überprüfe einmal deinen Vereinslink auf Sonderzeichen.
Es darf dort nichts anderes als ein Bindestrich verwendet werden. 

Sollte dort ein / oder Ähnliches enthalten sein, bitte einmal den Link unter Mein Verein > Vereinsdaten bearbeiten ändern.

**Comment by jh-new** [comment]
Hallo Herr Vallandi,

danke, das Problem ist gelöst.

Viele Grüße
Jörg Hülsey
