### ISSUE TITLE
Sortierung der Veranstaltung

### ISSUE THREAD

**Issue by Philip-Albrecht** [timvallandi/flvw-checkin#29]
![image](https://user-images.githubusercontent.com/71924151/94456977-3df2de80-01b4-11eb-9855-5de176dbbb9a.jpeg)

Die Sortierung sollte andersherum sein, sodass die nächste Veranstaltung oben angezeigt wird

**Comment by timvallandi** [comment]
Guter Einwand. 
Werden wir umsetzen.
