### ISSUE TITLE
[Wish] Password reset login

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#3]
Ein Passwort zurücksetzen fehlt bei der Anmeldemaske.

**Comment by timvallandi** [comment]
Wird mit dem nächsten Update umgesetzt

**Comment by mentor77** [comment]
Wann wird das neue Update veröffentlicht? Bzw. an wen kann ich mich wenden, wenn das Passwort zurückgesetzt werden soll. Ich kann mich seit 2 Tagen nicht mehr anmelden. MfG

**Comment by 1Parri1** [comment]
> Wann wird das neue Update veröffentlicht? Bzw. an wen kann ich mich wenden, wenn das Passwort zurückgesetzt werden soll. Ich kann mich seit 2 Tagen nicht mehr anmelden. MfG

in anderen Beiträgen, hieß es 01.10. aber ob das wirklich bis dahin umgesetzt wird, wird sich zeigen ^^
