### ISSUE TITLE
Benutzer anlegen

### ISSUE THREAD

**Issue by MaikOtto** [timvallandi/flvw-checkin#30]
Wie kann ich einen Benutzer der sich als Gast eingetragen hat, auch als Trainer nutzen mit derselben E-Mail-Adresse?

**Comment by timvallandi** [comment]
Wird mit dem neuen Release möglich sein. 
Wenn dann schon ein Zuschauer-Account vorhanden ist, wird es möglich sein diesem Account eine Trainerrolle zuzuweisen.

**Comment by timvallandi** [comment]
Mit gerade veröffentlichtem Release nun möglich
