### ISSUE TITLE
Zuscherdaten nicht einzugeben

### ISSUE THREAD

**Issue by Matzel92** [timvallandi/flvw-checkin#31]
Hi zusammen,
nach Einscannen des QR-Codes oder Kopieren des Links, öffnet sich das Formular zum Eingeben der Kontaktdaten nicht. Die Seite bleibt ohne Inhalt. Es ist nur das Hintergrundbild zu sehen(siehe Screenshot).

Verschiedene Personen haben es auf verschiedenen Endgeräten (Laptop, PC, iPhone und Andriod Smartphone) getestet.

Eine Veranstaltung ist zu diesem Zeitpunkt angelegt.

https://flvw.app/tusharpen/

Ich hoffe ihr könnt mir weiter helfen.
![Bildschirmfoto vom 2020-09-28 21-06-39](https://user-images.githubusercontent.com/72043281/94475007-c5e5e200-01ce-11eb-8ba3-a1e54c6986a3.png)

**Comment by timvallandi** [comment]
Bitte den / am Ende im Link entfernen. 
Dadurch kann die App den Link nicht sauber lesen. 

Es dürfen in den Links als Sonderzeichen nur Bindestriche enthalten sein.

Im nächsten Update werden Links dann auch zukünftig mit ungültigen Zeichen abgelehnt, sodass der Nutzer dann sofort einen anderen Link verwenden kann.

**Comment by Matzel92** [comment]
Danke für die schnelle Antwort.

Leider besteht das Problem immer noch :-(

https://flvw.app/tusharpen

**Comment by timvallandi** [comment]
Bitte über "Mein Verein" -> "Vereinsdaten bearbeiten" den Link anpassen. 
Da wird vermutlich "tusharpen/" stehen als Link

**Comment by Matzel92** [comment]
Problem gelöst

Danke für die superschnelle Hilfe

**Comment by Matzel92** [comment]
gelöst
