### ISSUE TITLE
Kontaktdaten werden überschrieben

### ISSUE THREAD

**Issue by jh-new** [timvallandi/flvw-checkin#32]
In meinem Account als Vorsitzender, werden die Kontaktdaten in meinem Account von anderen Nutzern überschrieben, nur mein Anzeigename und die Emailadresse bleiben

**Comment by timvallandi** [comment]
Problem ist bekannt und wird mit dem nächsten Release am 01.10. behoben.

**Comment by timvallandi** [comment]
Problem sollte nun behoben sein.
