### ISSUE TITLE
Vorstand als Rolle nur einmal vergeben?

### ISSUE THREAD

**Issue by tkoll** [timvallandi/flvw-checkin#35]
Leider kann ich die Rolle Vorstand nicht mehreren Personen vergeben, ist das richtig und so gewollt? Da bei uns mehrere Personen im Vorstand arbeiten, wäre eine Mehrfachvergabe sehr hilfreich, da somit mehrere Personen den Überblick behalten können.

**Comment by timvallandi** [comment]
Bitte einmal näher erläutern. Das sollte mehrfach möglich sein und habe ich auch schon mehrfach erfolgreich so durchführen können.
