### ISSUE TITLE
Auswahl anwesender Trainer

### ISSUE THREAD

**Issue by Alex4443** [timvallandi/flvw-checkin#36]
Hallo,

es sollte neben den Spielern auch eine Möglichkeit geben, auzuwählen welche Trainer anwesend sind. Sonst müssen diese ebenfalls extra eingetragen werden als Zuschauer.

Desweiteren gibt es auch Trainer, die zwei Mannschaften trainieren. Beim Anlegen eines Trainers kann allerdings nur eine Mannschaft ausgewählt werden.

**Comment by Philip-Albrecht** [comment]
Bei uns sind alle Trainer dem Team hinzugefügt und dann können die dort mit ausgewählt werden 👍🏼 funktioniert sehr gut bisher 😊

**Comment by timvallandi** [comment]
Diesen Weg würde ich auch empfehlen.

Diese Funktion bekommt erstmal weniger Priorität. Wird aber bald berücksichtigt werden, dass Trainer automatisch hinzugefügt werden zur Mannschaft.

**Comment by timvallandi** [comment]
Die Funktion, dass Trainern mehrere Mannschaften zugewiesen werden können, wird ab dem nächsten Release am 01.10. möglich sein.

**Comment by Alex4443** [comment]
Vielen Dank
