### ISSUE TITLE
Webseite nicht mehr erreichbar

### ISSUE THREAD

**Issue by jh-new** [timvallandi/flvw-checkin#37]
Die Web Seite ist am PC unter flvw.app nicht mehr erreichbar

**Comment by timvallandi** [comment]
Kann ich nicht bestätigen. 

Die Server sind online und die Seite ist über verschiedenste Geräte von mir erreichbar. 

Wird ein lokales Netzwerkproblem sein.

**Comment by jh-new** [comment]
Hallo Herr Valland,

bei mir am iPad geht es auch, nur über die normalen Browser am PC z.B.  über Chrome bekomme ich die Fehlermeldung.

Viele Grüße
Jörg

**Comment by jh-new** [comment]
Hallo Herr Valland,

über mein IPad habe ich auch kein Problem, aber vom Rechner über die üblichen Browser bekomme ich die Meldung: „die Web-Seite ist nicht verfügbar oder dauerhaft an eine neue Webadresse verschoben.“

Viele Grüße
Jörg

**Comment by timvallandi** [comment]
Hallo Jörg,

Kann ich leider nicht nachstellen den Fehler.
Wie gesagt es ist alles Online und ich konnte über den PC mit allen gängigen Browsern soeben auf die Seite zugreifen.

Deswegen wird es entweder am PC liegen oder am privaten Netzwerk.

Viele Grüße

Tim
Am 30. Sept. 2020, 15:44 +0200 schrieb jh-new <notifications@github.com>:
