### ISSUE TITLE
E-Mail Adresse bleibt trotz Löschens bestehen im Userstamm bestehen

### ISSUE THREAD

**Issue by tkoll** [timvallandi/flvw-checkin#38]
Löscht man ein Benutzer und will dann einen neuen Benutzer mit derselben E-Mail-Adresse anlegen, erhält man leider eine Fehlermeldung, dass diese E-Mail-Adresse schon vergeben ist.

Dies haben wir einmal normal nachgestellt und einmal schlug eine Anmeldung über Facebook fehl. Leider konnte man sich danach auch nicht mehr mit der bei Facebook hinterlegten Adresse registrieren.

**Comment by timvallandi** [comment]
Nach mehreren Tests kann ich diesen Fehler nicht bestätigen. 
Wenn ich beispielsweise den Trainer-Account lösche, dann warte ich bis ich auf die Übersicht zurückgeleitet werde und der Name nicht mehr in der Liste auftaucht. Wenn ich dann einen User mit der gleichen E-Mail Adresse anlege, dann kann ich ihn auch wieder erstellen ohne dass die beschriebene Fehlermeldung erscheint. 

Kannst du dein Vorgehen einmal näher erläutern ?

**Comment by tkoll** [comment]
Hallo, anbei eine nähere Erläuterung dazu mit Screenshots:

Ich habe nur ein Benutzer bei uns, versuche einen weiteren Vorstand anzulegen. Die E-Mail-Adresse ist also bei uns nicht belegt.
Unten kommt die Meldung, dass die E-Mail-Adresse aber schon belegt ist.

Was sein kann, ist dass er sich als normaler Benutzer registriert hat, damit er am Platz einchecken kann. Aber er muss ja zusätzlich bei uns als Vorstand an liegt Bar sein, auch wenn er auf anderen Plätzen als Besucher da war.

Im letzten Screenshot ganz unten findest du die Fehlermeldung.



Viele Grüße,
Tim

**Comment by tkoll** [comment]
Das zweite Problem kam auf, nachdem eine Anmeldung über Facebook fehlgeschlagen war, danach konnte man sich mit dieser E-Mail-Adresse, die bei Facebook hinterlegt war, nicht mehr als Besucher registrieren.

Viele Grüße,
Tim

**Comment by timvallandi** [comment]
Okay. Wenn er sich als Zuschauer registriert hat, dann bitte noch ein bisschen Geduld. 
Mit dem nächsten Release wird es auch möglich sein, dass ein als Zuschauer registrierter Nutzer in einen Vorstands-/Trainernutzer umbenannt werden kann.
