### ISSUE TITLE
[Bug] Anlegen von Auswärtsspielen

### ISSUE THREAD

**Issue by dati75** [timvallandi/flvw-checkin#39]
Beim Anlagen von Auswärtsspielen kann man den Hinzufügen Button nicht bestätigen - Speichern nicht möglich

**Comment by timvallandi** [comment]
Fehler wird mit einem Update im Laufe des Tages behoben

**Comment by Tho-Gra** [comment]
Sorry wenn ich frage... aber welchen Sinn macht es, ein Auswärtsspiel einzufügen?
Wenn ich Gast bin, muss ich doch in deren Liste... und brauche keine eigene erstellen?!

**Comment by timvallandi** [comment]
Die Export Funktion wird für Trainer noch freigeschaltet. 

Man kann dann ein Auswärtsspiel anlegen, seine Spieler abhaken und dann ein PDF exportieren welches man dann dem Gastverein geben kann :-) 

So in etwa ist die Funktion derzeit gedacht. 


Wir arbeiten auch schon an einer Gästeteam-Funktion für den Heimverein, sodass sich der Gast dann schnell bei einem Auswärtsspiel seine Teilnehmer eintragen kann. 
Näheres folgt in den nächsten Tagen.
