### ISSUE TITLE
[Bug] Zuschauer ohne Login geht nicht durch

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#4]
Anmeldung als Zuschauer ohne Registrierung geht nicht durch.

Verwendetes Gerät: Huawei P30 Lite New Edition
Browser: Google Chrome Version 85.0.4183.127

und 

Verwendetes Gerät: Win 10 Build 2004
Browser: Google Chrome Version 85.0.4183.121

**Comment by timvallandi** [comment]
Wird denn die Bestätigungsseite angezeigt oder kommt man vorher schon nicht weiter ? 

Erfolgte die Registrierung für eine bestimmte Veranstaltung oder eine „andere Veranstaltung“?

**Comment by 1Parri1** [comment]
> Wird denn die Bestätigungsseite angezeigt oder kommt man vorher schon nicht weiter ?

Es erscheint keine neue Seite.

> Erfolgte die Registrierung für eine bestimmte Veranstaltung oder eine „andere Veranstaltung“?

Sowohl als auch, Ich habe eine Veranstaltung ausgewählt, 2 Veranstaltung, und andere Veranstaltung. immer das gleiche resultat
![Screenshot 2020-09-26 145306](https://user-images.githubusercontent.com/71897230/94341231-05160680-0008-11eb-8723-060c68f91cf5.png)

**Comment by timvallandi** [comment]
Fehler gefunden. Update ist raus. Danke für die Mithilfe 👍
