### ISSUE TITLE
[Feature] Ändern von Terminserien

### ISSUE THREAD

**Issue by dati75** [timvallandi/flvw-checkin#40]
Aktuell sind nur einzelne Termine zu ändern, ein Ändern von Terminserien ist nicht möglich

**Comment by timvallandi** [comment]
Wird zunächst einmal nicht umgesetzt

**Comment by Dirk-1971** [comment]
Wenn dies derzeit noch nicht umgesetzt wird, können dann ganze Terminserien gelöscht werden, damit man diese dann neu und richtig anlegen kann?
