### ISSUE TITLE
[Feature] Änderung von Teams

### ISSUE THREAD

**Issue by dati75** [timvallandi/flvw-checkin#41]
Aktuell kann man unter Team bearbeiten nur das Team löschen. Schön wäre hier ein Änderung des Teamnames.

**Comment by timvallandi** [comment]
Team-Namen können aus technischen Gründen derzeit nicht editiert werden.

Wenn man den Team-Namen bearbeiten muss aufgrund eines Tippfehlers, muss man ein neues Team erstellen und entsprechend das andere Team löschen.

Es gibt derzeit wichtigere Dinge an denen wir arbeiten. Daher nun erstmal diese Lösung.

Zu einem späteren Zeitpunkt werde ich mich der Sache annehmen.
