### ISSUE TITLE
Gravierender Fehler beim erstellen eines Termins

### ISSUE THREAD

**Issue by Timo-1981** [timvallandi/flvw-checkin#42]
Hallo, unser Trainer hat einen Termin erstellt. Dieser ist jetzt gefühlt 100 mal bis ins Jahr 2021 gespeichert. Ich kann doch jetzt nicht alle Termine einzeln löschen. 

Löschen der Mannschaft hat auch nichts gebracht.

<img width="534" alt="Bildschirmfoto 2020-10-03 um 11 20 26" src="https://user-images.githubusercontent.com/71963978/94988057-c681ce00-056a-11eb-96a9-35e0978f7236.png">

**Comment by timvallandi** [comment]
Ja den Fehler hatte ich in meinem Verein auch schon.

Ich arbeite gerade an einer Lösung, sodass der Admin dann mehrere Termine auf einmal löschen kann.

**Comment by Timo-1981** [comment]
Sehr gut. Das hängt wohl damit zusammen, das die Webseite in dem Moment der Terminerstellung sehr träge war und man mehrfach auf den "Termin erstellen" Button gedrückt hat.

**Comment by timvallandi** [comment]
Ja richtig. Ich habe für das nächste Update folgende Features mit aufgenommen:

- Button zum Hinzufügen von Veranstaltungen wird deaktiviert und zeigt einen ladenden Zustand, sobald man ihn 1x betätigt hat. Somit können dann nicht mehr 100x die gleichen Veranstaltungen angelegt werden, sondern nur so viele wie angegeben. 

- Admins bzw. Vorstände können mehrere Veranstaltungen auf einmal löschen. Es wird keine Funktion zum bearbeiten von Serienterminen geben und die Trainer sollen auch nicht mehrere Veranstaltungen auf einmal löschen.

**Comment by timvallandi** [comment]
Features wurden wie beschrieben mit dem heutigen Update hinzugefügt.
