### ISSUE TITLE
Serientermine löschen

### ISSUE THREAD

**Issue by Hendrik2878** [timvallandi/flvw-checkin#43]
Ich habe versehentlich 30 Serientermine für Dienstag und Donnerstag bis zum 30.06.21 angelegt. Jetzt müsste ich diese einmal gelöscht haben, habe mit meinen Rechten aber keine Möglichkeit. Können Sie meinen Account einmal bereinigen, so dass ich die Terminserie neu hinterlegen kann?
Vielen Dank und Grüße aus Coesfeld, 
Hendrik Börnemann

**Comment by timvallandi** [comment]
Mit dem nächsten Update wird es eine Lösch-Funktion für Serientermine geben. Diese wird dann den Admins bzw. Vorständen zur Verfügung stehen.

**Comment by timvallandi** [comment]
Mit heutigem Update umgesetzt (Nur für Vorstände/Admins)

**Comment by Hendrik2878** [comment]
Ich habe mit einem Administrator gesprochen, leider läßt sich nur der aktuelle Monat löschen. Wäre es bitte möglich ganze Terminserien zu löschen? 
Danke und VG Hendrik Börnemann

**Comment by timvallandi** [comment]
Danke für den Hinweis.
Fehler ist korrigiert und jetzt kann dann auch der vollständige Zeitraum gelöscht werden.

**Comment by Hendrik2878** [comment]
Laut Admin ist es leider noch immer nicht möglich, ganze Terminserien zu löschen. Sobald dies umgesetzt ist, würde ich die App zur Nachverfolgbarkeit gerne nutzen.

**Comment by Hendrik2878** [comment]
Am PC ging das jetzt, am Tablet/Handy wohl noch nicht. Kann damit jetzt aber arbeiten... :-)
