### ISSUE TITLE
Trainer sollten auch Zuschauer manuell erfassen können.

### ISSUE THREAD

**Issue by Niko062** [timvallandi/flvw-checkin#45]
In der letzten Woche war es noch so, dass die Trainer keine Zuschauer manuell erfassen konnten und auch ein PDF-Export der Liste war für die Trainer nicht möglich. Es konnten lediglich die Spieler abgehakt werden. Wenn man beispielsweise den Trainern die Verantwortung an Trainingstagen überlässt, sollten diese zumindest die Zuschauer manuell erfassen können. 

Auch wenn noch ein paar Bugs drin sind, ist es eine enorme Erleichterung! Weiter so!

Gruß,
Niko

**Comment by timvallandi** [comment]
Diese Funktion sollte aber eigentlich funktionieren? 

Bitte nach dem heutigen Update nochmal versuchen
