### ISSUE TITLE
Terminart Vorschlag 

### ISSUE THREAD

**Issue by davidstuedemann** [timvallandi/flvw-checkin#46]
moin  
Ich hätte den Vorschlag,  dass man die Möglichkeit hat bspw. Besprechungs Termine zu erstellen  bspw. Für Trainersitzungen vorstandssitzung oder jahreshauptversammlung.

**Comment by timvallandi** [comment]
Gute Idee! Nehme ich mal mit in die ToDo-Liste auf.

**Comment by timvallandi** [comment]
Mit dem Update vom 20.10. wurde die Veranstaltungsart "Versammlung" hinzugefügt
