### ISSUE TITLE
PDF-Ausdruck der Zuschauer/Spieler-Liste fehlerhaft

### ISSUE THREAD

**Issue by Niko062** [timvallandi/flvw-checkin#47]
Ich bekomme nur sehr selten die komplette Liste angezeigt beim PDF-Export. Manchmal stehen beispielsweise von 19 Spielern nur 13 drauf oder bei dem 18. Spieler ist die Liste auf einmal abgehackt sichtbar.

Bei mehreren Versuchen klappt es dann irgendwann.

**Comment by timvallandi** [comment]
Den Fehler konnte ich bisher nicht nachstellen bzw. die Ursache feststellen. 
Tritt es nur auf einem bestimmten Gerät auf ?
