### ISSUE TITLE
Account Name falsch angezeigt

### ISSUE THREAD

**Issue by marcusgerke** [timvallandi/flvw-checkin#48]
Ich habe als Vereinsvorsitzender die Vorstandsmitglieder und Trainer angelegt und natürlich deren Namen und Mailadresse hinterlegt. Die Mitglieder können sich auch einloggen, werden aber auf den Seiten 
https://flvw.app/zuschauer/tickets
https://flvw.app/zuschauer/besuche
als "Marcus Gerke" begrüßt.

Checken Sie sich ein, werden sie mit ihrem eigenen Profil begrüßt. Wahrscheinlich ist das nur Kosmetik, aber dennoch enorm verwirrend.

Verein: https://flvw.app/svlangschede

**Comment by Philip-Albrecht** [comment]
Ja das Problem haben bei uns auch ein paar Trainer bzw. Vorstandsmitglieder.

**Comment by timvallandi** [comment]
Der Fehler sollte mittlerweile behoben sein.

Evtl. sonst mal unter Account bearbeiten noch einmal den Namen einmal anpassen.
