### ISSUE TITLE
Menu Icon fehlt

### ISSUE THREAD

**Issue by asbr90** [timvallandi/flvw-checkin#49]
Bei Nutzung auf einem Desktop wird unter der dem Menu-Punkt "Zu meinem Verein" keine Menu-Punkte, zum Navigieren, angezeigt. Umschaltung auf mobile Ansicht funktioniert.

**Comment by timvallandi** [comment]
Wahrscheinlich nur ein Temporärer Fehler. Vielleicht mal die Seite neu laden & den Browser-Cache leeren.
