### ISSUE TITLE
[Bug] Kontaktdaten werden nicht gespeichert

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#5]
Kontaktdaten werden nicht immer gespeichert, ich habe 2 Accounts. 
Einer ist Vorstand, bei dem wird es gespeichert.
Der andere als Trainer, da wird es nicht gespeichert.

Edit:
3. Account erstellt über den Vorstands Account. Eingeloggt und Profil ausgefüllt, es wurde gespeichert... nicht reproduzierbar ^^

**Comment by timvallandi** [comment]
Vielleicht Netzwerkprobleme / Fehler ? 
Wenn der Fehler nochmal auffällt, bitte nochmal einen Issue erstellen.

Diesen Fehler schließe ich zunächst einmal, da ich ihn bisher auch nicht reproduzieren konnte.
