### ISSUE TITLE
Lade dauer

### ISSUE THREAD

**Issue by davidstuedemann** [timvallandi/flvw-checkin#50]
Wir bekommen teilweise die Rückmeldung, dass die webapp trotz gutem Internet bzw. Mobilfunk empfang  längere Ladezustand hat   und manche Zuschauer deswegen lieber nochmal Stift und Zettel nutzen.

**Comment by timvallandi** [comment]
Normalerweise sollte die Ladedauer nicht länger als 1 Sekunde dauern wenn die Internetverbindung gut ist. 

Ich versuche da bald noch ein bisschen zu optimieren, aber man kann es leider nicht immer garantieren dass es sofort geladen ist. 
Manchmal dauert es auch nur beim allerersten Aufruf etwas länger, da von der WebApp bisher noch nichts im Cache liegt und somit erstmal ein paar Datensätze geladen werden müssen.

**Comment by davidstuedemann** [comment]
Bei mir lädt das meistens auch recht zügig   bei einem Trainer die Tage war das so aufm Handy mit 4g  hat Das Laden bei ihm teils länger als 30 sec gedauert   und bei mir selber Anbieter auch 4g hat es deutlich länger gedauert
