### ISSUE TITLE
Mannschaft gelöscht?!

### ISSUE THREAD

**Issue by marco443** [timvallandi/flvw-checkin#51]
Musste heute feststellen, das mein Team gelöscht ist, auch meine Veranstaltungen (3x Training) ist leider weg uns muss die Daten neu eingeben. Könnt ihr das nachvollziehen / wiederherstellen?!

Das wäre super!

**Comment by timvallandi** [comment]
Leider können wir das nicht mehr nachvollziehen bzw. wiederherstellen. 
Einmal gelöscht ist dann auch wirklich gelöscht. 

Administratoren bzw. Vorstände deines Vereins haben die Möglichkeit ein Team inkl. aller Veranstaltungen zu löschen. Bitte wende dich doch an einen Verantwortlichen in deinem Verein und frage nach warum er das gelöscht hat.

**Comment by marco443** [comment]
Bei den Verantwortlichen ist noch alles vorhanden und auch meine Veranstaltungen sind dort noch sichtbar. Nur bei mir nicht! 

Hatte zuletzt neu geladen u d dann war wieder alles da. Jetzt wieder alles weg!

**Comment by timvallandi** [comment]
Magst du mir mal die E-Mail Adresse von deinem Account und Vereinsnamen schicken ? Dann schaue ich mir das mal an ob da irgendwo ein Eintrag falsch ist.
Gerne auch sonst per Mail an info@timvallandi.de

Am 15. Okt. 2020, 21:42 +0200 schrieb marco443 <notifications@github.com>:

**Comment by marco443** [comment]
Marco.Menge@gmx.de

SC Halle 1919

Wir haben gerade mal etwas probiert. Mein Jugendleiter teilt mir mehrere Teams zu damit ich als Koordinator einen Überblick habe. Wenn er die Teams junger als E-Jugend freigibt, dann geht nix mehr bei mir. Nimmt er die wieder raus, kann ich wieder alles einsehen.

**Comment by timvallandi** [comment]
Ah okay dann weiß ich glaube ich wo das Problem liegen könnte... es ist aus technischen Gründen derzeit leider nicht möglich mehr als 10 Teams zuzuweisen. Wenn mehr als 10 Teams zugeordnet sind, könnten die Abfragen im Hintergrund dann derzeit scheitern.
Wenn mehr als 10 Teams benötigt werden, dann sollte man Übergangsweise diese Person als Vorstand zuordnen.
Es wird bald dann noch ein Update geben, sodass dann auch an Jugendleiter etc. gedacht ist.
Am 15. Okt. 2020, 21:52 +0200 schrieb marco443 <notifications@github.com>:

**Comment by marco443** [comment]
Wenn ich mehr als 10 Teams einsehen darf, als Rolle (Trainer), dann funktioniert das App nicht mehr...  bei Max 10 funktioniert es...

**Comment by timvallandi** [comment]
Okay.
Dann bitte noch etwas Geduld und wenn möglich zunächst einmal mit dem zuvor beschriebenen Workaround arbeiten.
Am 15. Okt. 2020, 22:41 +0200 schrieb marco443 <notifications@github.com>:
