### ISSUE TITLE
[Wish] weitere Mannschaft als Gäste bei Veranstaltung hinzufügen

### ISSUE THREAD

**Issue by dspenner** [timvallandi/flvw-checkin#52]
Eine schöne Funktion wäre, wenn man eine weitere Mannschaft aus dem Verein als Gäste der Liste hinzufügen könnte.
Hier könnte der Trainer / ein Vereinsverantwortlicher direkt die Haken entsprechend setzen und die Spieler seiner Mannschaft müssen nicht bei jeder Spiel einer anderen Mannschaft ihre Daten eintippen.

Beispielsweise, wenn sich eine 2. Mannschaft das eventuell darauf folgende Spiel der 1. Mannschaft ansieht.

**Comment by timvallandi** [comment]
Über die mittlerweile hinzugefügte "Zuschauerkontrolle" ist diese Funktion nun vorhanden. 

In der "Zuschauerkontrolle" einfach auf "Vereins-Person erfassen" klicken und schon kann man für eine gewählte Spieler einer Mannschaft als Zuschauer erfassen.
