### ISSUE TITLE
Der Trainer darf Zuschauer erfassen, aber nicht einsehen ob dieser bereits erfasst ist.

### ISSUE THREAD

**Issue by Tho-Gra** [timvallandi/flvw-checkin#53]
Guten Tag,

Als Trainer hat man aktuell die Möglichkeit einen Zuschauer zu erfassen... aber er kann nicht überprüfen ob ein Zuschauer dies bereits getan hat. 

Wir bitten darum, das ein Trainer auch in die Zuschauer Liste einsehen kann.
Anders wird man die "Lügner" (ich bin bereits in der Liste) - nicht entlarven können.

Danke

**Comment by timvallandi** [comment]
Wurde mit Update am 20.10. verändert. Trainer können nun die Namen der anwesenden Personen sehen.
