### ISSUE TITLE
APP hält mich für eine andere Person!

### ISSUE THREAD

**Issue by Dirk-1971** [timvallandi/flvw-checkin#58]
Mir ist gestern Abend aufgefallen, dass mich die APP mit einer anderen Person verwechselt! Unter "Meine Besuche" werden meine tatsächlichen Besuche angezeigt (siehe Bild).

![grafik](https://user-images.githubusercontent.com/71945909/96276500-63188700-0fd3-11eb-8150-39e826a01116.png)

Wenn ich nun auf die Anwesenheitsliste gehe, sehe ich anstatt meines Namens den Namen von unserem Trainer Florian Kroker in der Liste. Wo kann hier nun der Fehler liegen? Ich war wirklich mit meinem Accout eingeloogt.

![grafik](https://user-images.githubusercontent.com/71945909/96277298-5d6f7100-0fd4-11eb-80fc-cc61191ec717.png)

Auch am 06.10.2020 hatte ich mich eingewählt (Vorstandssitzung) und nicht Florian.

![grafik](https://user-images.githubusercontent.com/71945909/96277512-a7f0ed80-0fd4-11eb-94b0-999f500adbea.png)

**Comment by timvallandi** [comment]
Hallo Dirk,
Bitte entschuldige die späte Antwort. 
Bitte überprüfe doch mal unter "Mein Account" die eingetragenen Kontaktdaten und ändere sie gegebenenfalls.
