### ISSUE TITLE
Qr code

### ISSUE THREAD

**Issue by Dnstreuberg** [timvallandi/flvw-checkin#59]
Der qr Code für die Zuschauer Erfassung hat sich binnen 2 Tagen 3x geändert.... Das kann nicht sein... Niemand kommt auf die Seite über den qr code um sich dann anzumelden.

**Comment by timvallandi** [comment]
Der QR Code kann sich nicht ändern ... wenn dann hat ein Vorstand deines Vereins den Link für den Verein geändert worauf wir dann leider keinen Einfluss haben
