### ISSUE TITLE
[Wish] Teams nicht Editierbar

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#6]
Teams/Mannschaften sollten Editierbar gemacht werden, ich habe einen Schreibfehler im Namen und kann es nicht editieren.

**Comment by timvallandi** [comment]
Wird in der nächsten Version berücksichtigt

**Comment by 1Parri1** [comment]
Es ist leider noch nicht erledigt, oder es wird mir falsch angezeigt.
Löschen funktioniert, aber Editieren ist noch nicht möglich.

![image](https://user-images.githubusercontent.com/71897230/94487023-9049f480-01e0-11eb-8832-4ffc1ebfbb18.png)

**Comment by timvallandi** [comment]
Team-Namen können aus technischen Gründen derzeit nicht editiert werden.

Wenn man den Team-Namen bearbeiten muss aufgrund eines Tippfehlers, muss man ein neues Team erstellen und entsprechend das andere Team löschen. 

Es gibt derzeit wichtigere Dinge an denen wir arbeiten. Daher nun erstmal diese Lösung. 

Zu einem späteren Zeitpunkt werde ich mich der Sache annehmen.
