### ISSUE TITLE
Auswahl der Sportstätte für Zuschauer

### ISSUE THREAD

**Issue by BertiRe** [timvallandi/flvw-checkin#60]
Hallo Tim,

es wäre sinnvoll wenn Zuschauern/Besuchern ein Button auf der Startseite der App, zur Auswahl der Sportstätte (wenn mehrere angelgt), angezeigt würde. Nach dem Klick auf den Button sollten dann die angelegten Spiele/Veranstaltungen der jeweiligen Sportstätte angezeigt werden.

Grund hierfür: viele Zuschauer/Besucher die regelmäßig Heimspiele besuchen, haben den (einen z. B. flvw.app/verein) Link im Browser gespeichert und rufen diesen auf, ohne den QR-Code zu scannen, um einzuchecken. Bei z. B. drei angelegten Sportstätten und 3 unterschiedlichen Links ist dieses etwas umständlich.

Desweiteren wäre es sinnvoll die Sportstätte auch in die als PDF generierte Anwesenheitsliste zu implementieren.

Viele Grüße!

**Comment by timvallandi** [comment]
Gute Idee! 
Wird mit nächstem Update umgesetzt.
