### ISSUE TITLE
[Bug] Veranstaltung bearbeiten speichert nicht

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#61]
Das Bearbeiten von Veranstaltungen wird nicht Gespeichert.
Teilnehmerzahl wurde von 100 auf 300 geändert, zurück zur Übersicht, es werden 300 angezeigt. Seite neu geladen, es werden 100 angezeigt.
das gleiche bei Gastmannschaft etc.
Getestet am Handy und PC Google Chrome. Cache Gelöscht.

**Comment by timvallandi** [comment]
Okay schaue ich mir mal an. 
Bei meinen Tests grade konnte ich den Fehler noch nicht reproduzieren.
