### ISSUE TITLE
Sportstätten BEsucherzahl

### ISSUE THREAD

**Issue by davidstuedemann** [timvallandi/flvw-checkin#64]
Moin 
ich wollte vorschlagen, dass die Besucherzahl nicht pro Veranstaltung begrenzt wird sondern pro Sportstätte, das bspw. 2 spiele gleichzeitig auf einer Anlage stattfinden  und jeder Trainer für sich die Höchstzahl auswählt.

**Comment by timvallandi** [comment]
Hey David,

Gute Idee. Wir haben dieses Feature auch schon geplant und es wird in dieser Woche noch ein größeres Update geben wo dann auch dieses Feature mit berücksichtigt wird.
