### ISSUE TITLE
Veranstaltungen werden Gästen nicht angezeigt

### ISSUE THREAD

**Issue by mounty49** [timvallandi/flvw-checkin#65]
Habe als Vorstand eine Veranstaltung eines Teams für heute zu Testzwecken angelegt, danach ausgelogged und wollte an ihr dann als Gast/Zuschauer mit anderem Namen/E-Mail Adresse teilnehmen. Ich bekomme sie weder für eine einmalige Teilnahme noch nach einem Login (mit Daten ungleich denen des Vorstandes) angezeigt. Lediglich eine "andere Veranstaltung" des Vereins kann ich auswählen. Ich denke, dass das nicht Sinn der Sache ist. Wo liegt mein Fehler? Oder sind Zuschauer/Gäste gerades pandemiebedingt softwaretechnische ausgeschlossen???

**Comment by timvallandi** [comment]
Ist der Veranstaltung eine bestimmte Sportstätte zugeordnet?

**Comment by mounty49** [comment]
Nein, war es nicht. Mit der Sportstätte hat es dann geklappt. Vielen Dank
