### ISSUE TITLE
Doppelte Datensätze im Team bei Wiederverwendung des gleichen Teamnamens nach Löschung 

### ISSUE THREAD

**Issue by mounty49** [timvallandi/flvw-checkin#66]
Hatte Daten für ein neu angelegtes Team aus einer CSV-Datei hochgeladen und bemerkt, dass die Umlaute falsch dargestellt wurden. Habe dann das Team gelöscht und mit gleichem Namen danach neu erstellt sowie die Daten mit neuer CSV-Datei (UTF-8 Format) wieder hochgeladen. Jetzt hatte ich die Daten doppelt drin. Kann man die Dopplung nur vermeiden, wenn man einen neuen Teamnamen vergibt oder reicht es eine Zeit xyz zu warten? Wenn ja, wie groß ist xyz?
Danke!

**Comment by timvallandi** [comment]
Um sicher zu gehen, würde ich mal eine halbe Minute warten. Manchmal dauert die Bereinigung der Team-Mitglieder eine kurze Zeit.
