### ISSUE TITLE
Bildlaufleiste in Edge fehlt

### ISSUE THREAD

**Issue by mounty49** [timvallandi/flvw-checkin#67]
Beim Aufruf der Check In App auf einem PC (Windows 10) mit dem Edge-Browser fehlt z. B. bei der Anzeige größerer Teams die Bildlaufleiste zum Scrollen der Teammitglieder. Bei Firefox ist sie problemlos zu sehen. 

Sind Einstellungen im Edge Browser bekannt, die das Problem beheben?

Vielen Dank

**Comment by timvallandi** [comment]
Da ist mir leider keine Einstellung, die die Bildaufleiste einblendet.
