### ISSUE TITLE
[Bug] Zuschauerkontrolle Lädt ununterbrochen.

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#69]
es wurden 2 Test Veranstaltungen erstellt, beide mit Heimspielern und Schiedsrichter und einem Zuschauer über den Externen Link hinzugefügt.
Die Zuschauerkontrolle Lädt ununterbrochen und es passiert nichts.
![image](https://user-images.githubusercontent.com/71897230/102119918-1ec62d80-3e42-11eb-9ad8-1014d96c4c2b.png)

**Comment by timvallandi** [comment]
Ich kann den Fehler leider nicht nachstellen. Hab es mit einer aktuellen Version von Google Chrome auf MacOS getestet und in iOS und iPadOS. 

Hilft ein kompletter Reload der Seite bei diesem Problem? Mit welchem Gerät / Browser hast du es getestet? 

<img width="874" alt="Bildschirmfoto 2020-12-14 um 20 07 20" src="https://user-images.githubusercontent.com/71084009/102123996-fd684000-3e47-11eb-937f-b8a1af783237.png">

**Comment by 1Parri1** [comment]
PC
Win 10 Pro Build 2004
Google Chrome Version 87.0.4280.88 (Offizieller Build) (64-Bit)
Microsoft Edge Version 87.0.664.60 (Offizielles Build) (64-Bit) <-- Basiert mittlerweile auch auf Chrome.
Mozilla Firefox Version 84.0 (64-Bit) <-- extra Installiert.

Handy
Huawei P30 Lite
Google Chrome Version 87.0.4280.101

Cache wurde geleert.

Hier die Veranstaltungen.
![image](https://user-images.githubusercontent.com/71897230/102243057-082fdd00-3efb-11eb-9052-899c3aa7b50c.png)

**Comment by timvallandi** [comment]
Ich glaube, ich habe den Fehler gefunden. Die Zuschauerkontrolle kann derzeit noch nicht damit umgehen, dass keine Sportstätte angelegt ist. Dies wird bald noch behoben.

Als Workaround bis dahin empfehle ich folgendes: 

- Unter "Verein" -> "Sportstätten verwalten" mal bitte min. 1 Sportstätte anlegen.
- Danach dann bitte die Veranstaltungen bearbeiten und einer Sportstätte zuweisen. 

Nun sollte die Zuschauerkontrolle passend laden.

**Comment by 1Parri1** [comment]
Workaround Funktioniert! Danke
