### ISSUE TITLE
[Bug] Erstellter Benutzer in keinem Team

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#7]
Vom Vorstand Neu erstellter Benutzer wird keiner Mannschaft zugewiesen oder es wird nicht angezeigt.

**Comment by timvallandi** [comment]
Fehler gefunden.

Es lag daran, dass die Accounts noch nicht richtig generiert wurden.
Wenn ein vom Verein erstellter Vorstand einen Trainer erstellt hat, dann verwies der Trainer-Account auf den Vorstandsaccount und nicht auf den Vereinsaccount, sodass die Veranstaltungen nicht im Verein angelegt wurden.

Habe den Fehler für zukünftige Accounts geändert und die bisher erstellten Accounts des SV Bossendorf manuell angepasst.

Bitte mal testen. Es sollte jetzt funktionieren

**Comment by 1Parri1** [comment]
Funktioniert, kann geschlossen werden Danke!
