### ISSUE TITLE
[Wish] Startup Popup ist zu penetrant

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#70]
Wenn man viel auf der Seite unterwegs ist, dann nervt es sehr wenn das Popup immer wieder auftaucht wenn man auf die Startseite/Veranstaltungsseite zurück geht.

Wäre es möglich dieses Popup für eine Woche auszublenden/bis zum nächsten update?

![image](https://user-images.githubusercontent.com/71897230/102120597-11f60980-3e43-11eb-8f48-07c60a07704a.png)

**Comment by timvallandi** [comment]
Normalerweise sollte das Popup nach dem Klick auf "OKAY!" nie mehr angezeigt werden.

**Comment by 1Parri1** [comment]
Getestet mit diesen Systemen/Browsern, es wird immer wieder angezeigt sobald man auf die Startseite/Veranstaltungsseite zurückkehrt.


PC
Win 10 Pro Build 2004
Google Chrome Version 87.0.4280.88 (Offizieller Build) (64-Bit)
Microsoft Edge Version 87.0.664.60 (Offizielles Build) (64-Bit) <-- Basiert mittlerweile auch auf Chrome.
Mozilla Firefox Version 84.0 (64-Bit) <-- extra Installiert.

Handy
Huawei P30 Lite
Google Chrome Version 87.0.4280.101

Cache wurde geleert.
