### ISSUE TITLE
Trainer erstellen mit bereits registrierter Mail -Adresse

### ISSUE THREAD

**Issue by davidstuedemann** [timvallandi/flvw-checkin#72]
Ich wollte ein Trainer erstellen, die Person hatte sich bereits mit ihrer Mail-Adresse als Zuschauer registriert und nun kann ich diese Mailadresse nicht nutzen um ihn als Vereinsbenutzer zu registrieren.

![Screenshot 2021-01-02 145847](https://user-images.githubusercontent.com/72359328/103458711-16f3fd80-4d0b-11eb-9611-79e86a8d5697.png)

**Comment by timvallandi** [comment]
Das Problem sollte jetzt nicht mehr auftreten. 
Ich konnte es in mehreren Tests bisher nicht mehr nachstellen.

Daher bitte noch einmal probieren.

**Comment by davidstuedemann** [comment]
Habe das jetzt gerade nochmal versucht.
Leider ist der Fehler weiterhin aufgetreten.

**Comment by timvallandi** [comment]
Hm okay das ist merkwürdig.

Kannst du mir einmal die Mail-Adresse nennen für die du versuchst den Account zu erstellen? 

Gerne auch per Mail an info@timvallandi.de. 


Dann gehe ich dem ganzen mal auf den Grund.

**Comment by davidstuedemann** [comment]
Habe eine Mail geschickt mit den Infos.

Vielen Dank fürs erstellen der Software und den Support
