### ISSUE TITLE
Vereinsbenutzer anlegen nicht möglich

### ISSUE THREAD

**Issue by andremeyerLC** [timvallandi/flvw-checkin#73]
Hallo, 

beim Anlegen neuer Vereinsbenutzer werden keine Mails an die Mailadressen versendet. Ein Fehler {} wird kurz angezeigt. Beim erneuten Versuch wird der Fehler angegeben, dass die Mail Adresse schon einen Account hat. Wie schon in einem anderen Issues vom 02.01.21 Trainer erstellen mit bereits registrierter Mail -Adresse #72 wird der Fehler angezeigt.
![image](https://user-images.githubusercontent.com/77157383/104022098-19010500-51c0-11eb-9918-1f932ca595ab.png)

**Comment by andremeyerLC** [comment]
Mir ist es weiterhin nicht möglich, die gewünschten Trainer/innen anzulegen. Beim weiten Versuch wird der im Bild angegeben Fehlercode angegeben. Dabei haben die Trainer auf die nicht verschickte automatische Einladung nicht angemeldet. Ein zurücksetzten des Passworts ist somit auch nicht möglich. Es scheint sich, bis zur Trainingswiederaufnahme zwar noch zu ziehen, dennoch möchte ich, nochmals um Hilfe bitten.

**Comment by timvallandi** [comment]
Schick mir doch bitte einmal folgende Infos an info@timvallandi.de

E-Mail Adresse des Accounts
und
E-Mail Adresse für den neuen Trainer Account.

Dann prüfe ich das mal.
Am 21. Jan. 2021, 17:11 +0100 schrieb andremeyerLC <notifications@github.com>:

**Comment by andremeyerLC** [comment]
Hallo Herr Vallandi, 

Konnten Sie uns schon weiterhelfen? Falls nötig, wäre es auch möglich, alle Trainer einmal zurückzusetzen. Bis lang sind nur 3 Trainer von uns eingetragen.  Leider gibt es auch ein Problem beim „Vereinsbenutzer verwalten“. 

Ich verbleibe mit sportlichen Grüßen


Andrè Meyer                         
Nachwuchskoordinator 

Leichtathletik-Club Paderborn e.V. 
Ahornallee 20 
33106 Paderborn 

Telefon (g): +49 (0)5251-7097440 
E-Mail: andre.meyer@lcpaderborn.de 
Web: www.lcpaderborn.de
