### ISSUE TITLE
Personen aus Benutzerdatenbank zu Teams / Veranstaltungen hinzufügen

### ISSUE THREAD

**Issue by NGoevert** [timvallandi/flvw-checkin#76]
Guten Tag,

zunächst ein herzliches Dankeschön für die Bereitstellung der FLVW-App!

Zur Personenerfassung habe ich eine Frage und einen Vorschlag:

Sehe ich das richtig, dass Trainer und Betreuer explizit in "ihren" Teams als Mitglieder erfasst werden sollten (um sie bei Anwesenheit einfach abhaken zu können oder als Zuschauer / Vereins-Person erfassen zu können)?

Denkbar wäre, dass Personen, denen ein Team zugeordnet wird, automatisch in die Liste der Teammitglieder aufgenommen werden. Für Personen mit der Rolle Vorstand könnte man ein virtuelles Team Vorstand erzeugen.

Viele Grüße
Norbert Gövert

**Comment by fgiesecke** [comment]
Hallo Norbert,
schau Dir mal https://github.com/timvallandi/flvw-checkin/issues/36 an.

**Comment by NGoevert** [comment]
Alles klar und vielen Dank, Florian. So wird es gemacht.

Viele Grüße
Norbert
