### ISSUE TITLE
Alle letztes Jahr angelegten Daten der Spieler bzw die Spieler sind weg

### ISSUE THREAD

**Issue by BG-Frank** [timvallandi/flvw-checkin#77]
Hallo,
ich hatte für unseren Verein Spvg.Blau-Gelb Schwerin E.V. alle Spielerdaten sämtlicher Teams eingetragen.
Nun da der Restart nicht mehr lange dauert wollte ich heute anfangen und Veranstaltungen eintragen und dabei ist mir aufgefallen das die  Daten der Spieler bzw die Spieler in den Teams nicht mehr vorhanden sind.
Lassen die sich aus einem Backup wiederherstellen. Möchte nicht wieder alles händisch eintragen.
Vielen Dank im Voraus

**Comment by timvallandi** [comment]
Wir verfügen leider nicht über Backups, die über eine solche Zeit zurückgehen. Daher kann ich dir leider nicht die gelöschten Daten vom Ende des letzten Jahres wiederherstellen.
