### ISSUE TITLE
[Bug] Erstellter Benutzer verschwunden

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#8]
Erstellte Benutzer durch den Vorstand, tauchen nicht in der Vereinsbenutzer Übersicht auf.

**Comment by timvallandi** [comment]
Da ja scheinbar mehrere Dinge nicht richtig funktionieren:
Bitte einmal versuchen den Browser-Cache zu löschen und dann erneut auf die Seite.

Wenn es nicht hilft, Teil mir mal bitte deinen Verein mit dem Du dich registrierst hast. Dann schaue ich mir das mal an.

**Comment by 1Parri1** [comment]
Cache wurde gelöscht.
Neuer Benutzer erstellt, er taucht in der Liste nicht auf.
getestet am PC mit Chrome und Edge, am Handy über Chrome

Verein SV Bossendorf

**Comment by timvallandi** [comment]
Schaue ich mir an. Ich melde mich wenn ich den Fehler gefunden habe.

**Comment by timvallandi** [comment]
Fehler gefunden.

Es lag daran, dass die Accounts noch nicht richtig generiert wurden.
Wenn ein vom Verein erstellter Vorstand einen Trainer erstellt hat, dann verwies der Trainer-Account auf den Vorstandsaccount und nicht auf den Vereinsaccount, sodass die Veranstaltungen nicht im Verein angelegt wurden.

Habe den Fehler für zukünftige Accounts geändert und die bisher erstellten Accounts des SV Bossendorf manuell angepasst.

Bitte mal testen. Es sollte jetzt funktionieren

**Comment by 1Parri1** [comment]
Funktioniert, kann geschlossen werden Danke!

**Comment by BertiRe** [comment]
Das gleiche Problem auch bei dem Verein TuRa Elsen. Benutzer (Trainer) durch Vorstand ersellt und Mannschaft zugeordnet. Benutzer unter "Angelegte Nutzer" nicht vorhanden. Benutzer (Trainer) kann sich zwar einloggen, sieht aber zugeordnete Mannschaft nicht.

**Comment by timvallandi** [comment]
Prüfe ich und korrigiere es dann bei dem Verein auch entsprechend

**Comment by timvallandi** [comment]
> Das gleiche Problem auch bei dem Verein TuRa Elsen. Benutzer (Trainer) durch Vorstand ersellt und Mannschaft zugeordnet. Benutzer unter "Angelegte Nutzer" nicht vorhanden. Benutzer (Trainer) kann sich zwar einloggen, sieht aber zugeordnete Mannschaft nicht.

Habe es beim Verein korrigiert.
