### ISSUE TITLE
Handbuch (Seite 8): Datenimport und Zeichenkodierung

### ISSUE THREAD

**Issue by NGoevert** [timvallandi/flvw-checkin#81]
Hallo,

das Importieren von Daten aus CSV-Dateien funktioniert einwandfrei. Auch Umlaute und andere Nicht-ASCII-Zeichen werden problemlos verarbeitet. Im Handbuch auf Seite 8 kann daher der Hinweis auf die Ersetzung diakritischer Zeichen gelöscht werden.

Auf derselben Seite ist noch ein kleiner Fehler: Im Import-Beispiel für die Formatierung der CSV-Datei wurde die Spaltenüberschrift "Strasse" verwendet. Die Spaltenüberschrift sollte jedoch "Straße" lauten.

Viele Grüße
Norbert

**Comment by timvallandi** [comment]
Danke für den Hinweis. Die Info habe ich an die zuständige Stelle weitergeleitet.
