### ISSUE TITLE
Auswertung über Gastspieler

### ISSUE THREAD

**Issue by abanhold** [timvallandi/flvw-checkin#82]
Man hat ja die Möglichkeit Gastspieler zu erfassen. Toll wäre es, wenn man eine Auswertung über die Gastspieler machen könnte. Also dass man sehen könnte, dass Max Mustermann bereits 3x zum Probetraining war und es Zeit wird, dass er sich im Verein anmeldet. Wir als Verein hätten dadurch eine Übersicht, wieviele Spieler in den unterschiedlichsten Mannschaften derzeit zur Probe trainieren.

**Comment by timvallandi** [comment]
Guter Vorschlag, allerdings ist das Ziel der CheckIn-App lediglich das einfache Erfassen von Kontaktlisten zur COVID19-Rückverfolgung und dementsprechend wird eine solche Auswertungs-Funktion nicht umgesetzt.
