### ISSUE TITLE
Checkout als registrierter User nicht vorhanden

### ISSUE THREAD

**Issue by fgiesecke** [timvallandi/flvw-checkin#84]
Ich bin ein registrierter User und habe mich per QR-Code auf dem Sportplatz eingecheckt.
Am Ende des Vorgangs erhalte ich die Meldung "Willkommen, Du hast derzeit keine aktiven Checkins". Als Vorstand sehe ich mich in der Anwesenheitsliste.
Ich kann mich als User aber nicht selbst wieder abmelden.

Wenn ich mich als nicht registrierter User auf dem Sportplatz einchecke, erhalte ich eine Bestätigungsseite mit Namen, Uhrzeit und link zum "Auschecken". Über den Link kann ich. mich auch erfolgreich abmelden.

Was läuft hier falsch? Hat einer von euch es geschafft, sich als registrierter User abzumelden? Oder muss ich meinen Mitgliedern sagen, dass sie sich nicht registrieren dürfen...

**Comment by timvallandi** [comment]
Kannst du mir verraten über welchen Gerät und mit welchem Browser du es probiert hast? 

Ich kann diesen Fehler bisher überhaupt nicht nachstellen. Es wird mir immer alles korrekt angezeigt und ich habe auch als registrierter Nutzer die Option mich auszuchecken.

**Comment by timvallandi** [comment]
Ich konnte einen Fall finden, wo der CheckIn als User nicht angezeigt wurde. 
Der Bug wurde behoben. Ich hoffe, dass die Fehlerbehebung auch in deinem Fall weiterhilft. 

Wenn nicht bitte noch einmal melden.

**Comment by fgiesecke** [comment]
Hallo @timvallandi , danke für Deine Hilfe, leider hat es noch nicht funktioniert.

Nachstellung:
Ich bin registriertes Mitglied, Rolle Vorstand. Ich habe den Link zum Check-in des Platzes auf meinem Mac im Safari-Browser aufgerufen. Login ausgeführt und dann "Andere Veranstaltung des Vereins" ausgewählt, Zeit 30 Minuten ausgewählt und Button Check-In bestätigt.
Auf der dann folgenden Seite erhalte ich die Meldung "Du hast derzeit keine aktiven CheckIns".
Selbes habe ich im Firefox auf dem Mac probiert sowie im Safari auf dem iPhone.
Ich habe es auch mit einer Veranstaltung (Training) probiert und auch noch ein weiteres Familienmitglied erfasst.
Auch mit einem neu registrierten Account bekomme ich keinen Link zum Checkout.

Sobald ich das Checkin als nicht registrierter Anwender (Einmalige Erfassung) mache, bekomme ich den Checkout Link angezeigt.

https://user-images.githubusercontent.com/7612848/113421699-d8361800-93cb-11eb-8e41-0d7a613ab3ae.mp4

Ich habe mir mal unseren Link angesehen, da sind sehr viele Sonderzeichen drin, vielleicht ist das auch eine Ursache? https://flvw.app/s.v.rot-wei%C3%9Fmastholte/tennisplatz

**Comment by timvallandi** [comment]
Hey danke für die zahlreichen Infos! 
Ich vermute, dass es nicht an den Sonderzeichen im Link liegt, denn sonst würde es auch Probleme beim Abruf der aktuellen Veranstaltungen etc. geben. Dennoch würde ich evt. mal überlegen, ob man nicht einen einfacheren Link für den Verein verwendet. Denn es gibt immer mal wieder Personen, die keinen QR-Code scannen können oder wollen und lieber den Link manuell eingeben. Und da ist dann ein kürzerer Link auf jeden Fall für alle Beteiligten einfacher. 

Aber zurück zu deinem Problem:
Scheinbar schlägt intern bei dir eine Abfrage zur Datenbank fehl, sodass die aktuell aktiven Besuche nicht gefunden werden können. Ich versuche noch einmal ein paar Optimierungen vorzunehmen und hoffe dass damit dann auch deine Probleme behoben sind. 

Ich habe es auch auf meinem Mac mit Safari & Google Chrome getestet und auch auf iOS mit Safari & Google Chrome. Bei mir wird alles immer korrekt geladen. 

Ich melde mich hier, sobald ein neues Update veröffentlicht wurde.

**Comment by timvallandi** [comment]
Eventuell einmal versuchen deinen Browser-Cache zu löschen. Bei manchen Fehlern kann es helfen.

**Comment by fgiesecke** [comment]
Hi,
um mal zu probieren... ich habe den Link vom Verein geändert um die Sonderzeichen loszuwerden, hatte aber keinen Effekt. flvw.app/rwm/
Browser-Cache ist gelöscht bzw. ich habe einen ganz jungfräulichen Rechner versucht. überall läuft es gleich.
unter meine Besuche wird mein aktueller Check-In angezeigt, unter meine aktiven Check-Ins aber nicht.

Ich habe es auch mit unterschiedlichen Plätzen von uns versucht und ich habe unterschiedliche Emailadressen für die Registrierung versucht.

**Comment by timvallandi** [comment]
Ich habe die Seite des aktiven User-CheckIns nochmal angepasst und nun sollte die Möglichkeit des Checkouts auch endlich werden. 

Bitte gib mir doch eine kurze Rückmeldung, ob es nun funktioniert.

**Comment by fgiesecke** [comment]
Guten Morgen Tim,
ja, es hat sich was getan...
Die Seite nach dem Check-In ist jetzt komplett leer. 
![09-04-_2021_07-44-47](https://user-images.githubusercontent.com/7612848/114134314-d1496100-9907-11eb-9aae-c2fcf5726aae.png)

Wenn ich auf Meine aktiven Checkins klicke, bekomme ich aber jetzt meinen Checkin angezeigt.
![09-04-_2021_07-45-18](https://user-images.githubusercontent.com/7612848/114134316-d27a8e00-9907-11eb-94ff-99576648f753.png)

Klicke ich dort dann auf den Eintrag, lande ich wieder auf der leeren Seite.

**Comment by timvallandi** [comment]
Magst du auf der leeren Seite im Firefox einmal die Tastenkombination CMD + Opt + I drücken und mir einmal den Auszug der Error-Konsole schicken? 

Das ist ja doch sehr merkwürdig so langsam.

**Comment by fgiesecke** [comment]
[vue-router] Named Route 'Vereinsseite' has a default child route. When navigating to this named route (:to="{name: 'Vereinsseite'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead. vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Meine Tickets", path: "/zuschauer/tickets/:ticket" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/wk/:verein/:veranstaltung" } vue-router.esm.js:17:47
[vue-router] Named Route 'Vereinsseite' has a default child route. When navigating to this named route (:to="{name: 'Vereinsseite'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead. vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/erfassen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/vervollstaendigen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/:sportstaette/erfassen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/:sportstaette/vervollstaendigen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/:sportstaette/zuschauer/:zuschauer" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/zuschauer/:zuschauer" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Vereinsseite", path: "/:verein" } vue-router.esm.js:17:47
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html vue.runtime.esm.js:8428:45
Object { verlassen: Getter & Setter, aktivitaet: Getter & Setter, person: Getter & Setter, veranstaltung: Getter & Setter, zutritt: Getter & Setter, weitere_personen: Getter & Setter, sportstaette: Getter & Setter, verein: Getter & Setter, anwesenheit: Getter & Setter, id: "axgxrRbY43xaojyMluyf", … }
ticket.vue:580:17
TypeError: _vm.besuch.verein.verein is undefined
    render webpack:///./src/components/zuschauer/ticket.vue?./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"097d2096-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options:701
    VueJS 7
vue.runtime.esm.js:1887:13
TypeError: _vm.besuch.verein.verein is undefined
    render webpack:///./src/components/zuschauer/ticket.vue?./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"097d2096-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options:701
    VueJS 7
vue.runtime.esm.js:1887:13
TypeError: _vm.besuch.verein.verein is undefined
    render webpack:///./src/components/zuschauer/ticket.vue?./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"097d2096-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options:701
    VueJS 7
        _render
        updateComponent
        get
        run
        flushSchedulerQueue
        nextTick
        flushCallbacks
vue.runtime.esm.js:1887:13
    VueJS 10

​

![09-04-_2021_09-00-11](https://user-images.githubusercontent.com/7612848/114141667-32763200-9912-11eb-905e-0f6d7879f2fc.png)

**Comment by fgiesecke** [comment]
[vue-router] Named Route 'Vereinsseite' has a default child route. When navigating to this named route (:to="{name: 'Vereinsseite'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead. vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Meine Tickets", path: "/zuschauer/tickets/:ticket" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/wk/:verein/:veranstaltung" } vue-router.esm.js:17:47
[vue-router] Named Route 'Vereinsseite' has a default child route. When navigating to this named route (:to="{name: 'Vereinsseite'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead. vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/erfassen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/vervollstaendigen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/:sportstaette/erfassen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/:sportstaette/vervollstaendigen" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/:sportstaette/zuschauer/:zuschauer" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Übersicht", path: "/:verein/zuschauer/:zuschauer" } vue-router.esm.js:17:47
[vue-router] Duplicate named routes definition: { name: "Vereinsseite", path: "/:verein" } vue-router.esm.js:17:47
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html vue.runtime.esm.js:8428:45
Object { verlassen: Getter & Setter, aktivitaet: Getter & Setter, person: Getter & Setter, veranstaltung: Getter & Setter, zutritt: Getter & Setter, weitere_personen: Getter & Setter, sportstaette: Getter & Setter, verein: Getter & Setter, anwesenheit: Getter & Setter, id: "axgxrRbY43xaojyMluyf", … }
ticket.vue:580:17

**Comment by timvallandi** [comment]
Danke! Starte jetzt nochmal bitte einen Versuch!

**Comment by fgiesecke** [comment]
Ja, das sieht sehr gut aus. Ich bekomme meinen Checkin angezeigt und kann mich dann auch abmelden.
etwas verwirrt mich aber: da wird als Person Jürgen Schlepphorst angezeigt und nicht mein Name?
Jürgen hat mal die initiale Registrierung gemacht.
![09-04-_2021_10-00-41](https://user-images.githubusercontent.com/7612848/114148929-9bfa3e80-991a-11eb-9376-42b47f6c7cf6.png)

**Comment by timvallandi** [comment]
Schau mal im Menu unter "Account verwalten" nach. Da ist dann wahrscheinlich noch ein falscher eingetragen.

**Comment by fgiesecke** [comment]
Unter Accout steht mein Name in meinem Account...

**Comment by timvallandi** [comment]
Hast du denn den Account übernommen oder hast du einen eigenen Vorstandsaccount?

**Comment by fgiesecke** [comment]
Ich habe einen neuen Account angelegt und der hat dann Vorstandsrechte bekommen, d.h. der Account von Jürgen existriert auch noch.

**Comment by timvallandi** [comment]
Okay, danke für dein Feedback.

Jetzt sollte wirklich alles passen, wenn du dich als registrierter für eine Veranstaltung anmeldest.

**Comment by fgiesecke** [comment]
Hallo,
JAAAA das sieht super aus. Ich kann mich ein- und auschecken und sehe die Historie.

Danke
