### ISSUE TITLE
[Bug] Als Trainer keine Veranstaltung

### ISSUE THREAD

**Issue by 1Parri1** [timvallandi/flvw-checkin#9]
Als Trainer kann keine Veranstaltung erstellt werden, oder ist nicht sichtbar.

**Comment by timvallandi** [comment]
Wird nach Klick auf den Hinzufügen-Button keine Veranstaltung angelegt oder an welcher Stelle genau funktioniert das Hinzufügen nicht?

**Comment by 1Parri1** [comment]
Das erstellen der Veranstaltung scheint zu funktionieren, aber sie Taucht nicht in der Übersicht auf. 
Weder im Trainer Account noch im Vorstands Account. 
Mit dem Vorstands Account kann ich allerdings Veranstaltungen erstellen.

**Comment by timvallandi** [comment]
Taucht die Veranstaltung gar nicht auf oder nur direkt nach dem Hinzufügen nicht ?

**Comment by timvallandi** [comment]
Probier es nochmal aus.
Ich habe mir euren Vereins-Account mal angesehen ... so wie da die Datenstruktur aufgebaut ist, sollte es jetzt normalerweise funktionieren.  

Die Tabs "GEPLANT" - "HEUTE" - "VERGANGEN" werden bei meinen Tests auf der Seite alle immer ohne Probleme geladen.

**Comment by 1Parri1** [comment]
Mit dem Vorstands Account kann ich ohne weiteres Veranstaltungen jeder Art erstellen.
Mit einem vom Vorstand erstellten Trainer Account (wird nicht in der Vereinsbenutzer Übersicht angezeigt) funktioniert es nicht eine Veranstaltung zu erstellen. Die Maske zum erstellen schließt sich, keine Fehlermeldung. Die Seite mit Tabs "GEPLANT" - "HEUTE" - "VERGANGEN" ist leer. 
Mit dem Vorstands Account sind die Veranstaltungen auch nicht sichtbar.

**Comment by timvallandi** [comment]
Fehler gefunden. 

Es lag daran, dass die Accounts noch nicht richtig generiert wurden. 
Wenn ein vom Verein erstellter Vorstand einen Trainer erstellt hat, dann verwies der Trainer-Account auf den Vorstandsaccount und nicht auf den Vereinsaccount, sodass die Veranstaltungen nicht im Verein angelegt wurden.

Habe den Fehler für zukünftige Accounts geändert und die bisher erstellten Accounts des SV Bossendorf manuell angepasst. 

Bitte mal testen. Es sollte jetzt funktionieren

**Comment by 1Parri1** [comment]
Funktioniert, kann geschlossen werden Danke!
