### ISSUE TITLE
[wish] Sichtbarkeit der "Sportstätte" bei einer erstellten Veranstaltung

### ISSUE THREAD

**Issue by rohnerac** [timvallandi/flvw-checkin#91]
Wäre es möglich, bei einer bereits erstellten Veranstaltung in der Rubrik "Veranstaltungen", auch die zugeordnete Sportstätte mit anzuzeigen?

Wir haben mehrere Sportplätze und aktuell muss man immer umständlich die Veranstaltung öffnen und dann auf Veranstaltung bearbeiten gehen, um zu sehen welche Sportstätte beim Termin hinterlegt ist. Gerade dann, wenn z.B. eine Mannschaft auf 2 Sportstätten gesplittet ist, ist dies bei der Erfassung umständlich.

![FVM_Veranstaltung](https://user-images.githubusercontent.com/83266818/116191973-7c8e4e80-a72d-11eb-8d3d-315398d3d7eb.jpg)

**Comment by rohnerac** [comment]
Nochmal zur Erinnerung.

**Comment by rohnerac** [comment]
@timvallandi

**Comment by rohnerac** [comment]
Vielen Dank für die schnelle Umsetzung!

**Comment by timvallandi** [comment]
Kein Problem!
