### ISSUE TITLE
Anwesenheit für Trainingsteilnehmer wird nicht ausgegeben

### ISSUE THREAD

**Issue by fgiesecke** [timvallandi/flvw-checkin#92]
Hallo Tim,
wir erfassen die Teilnehmer eines Trainings über die Trainer, die einen Haken in dem Termin setzen für sich und die Kinder.
Die Trainer und auch die Sportler werden aber nicht in den Anwesenheitslisten ausgegeben.
Die Auswertung habe ich sowohl versucht als Besuchsart Sportler als auch als Besuchsart Alle auszugeben, sie sind aber leer.

Danke
Florian

**Comment by timvallandi** [comment]
Hallo Florian,

Das muss ich prüfen. 
Normalerweise sollte die Liste gefüllt sein. 

Ist denn die Anwesenheitsliste in der einzelnen Veranstaltung gefüllt? Oder ist diese Anwesenheitsliste auch leer?

**Comment by fgiesecke** [comment]
Guten Morgen Tim,
die Anwesenheitsliste an der Veranstaltung kann erstellt werden und darin werden alle Teilnehmer auch ausgegeben.

**Comment by fgiesecke** [comment]
Hallo Tim,
bei meinem letzten Test vor ein paar Tagen funktionierte es nun.
