### ISSUE TITLE
Zuschauerkontrolle - Anmeldungen suchen: Suche funktioniert nicht?

### ISSUE THREAD

**Issue by NGoevert** [timvallandi/flvw-checkin#94]
Guten Abend,

für kommenden Samstag habeich eine Wettkampfveranstaltung angelegt, zu der sich auch bereits 25 Personen vorangemeldet haben. Wenn ich in der Zuschauerkontrolle die Funktion "Anmeldungen suchen" aufrufen und im Suchfeld zu tippen beginne, werden keine entsprechenden Suchergebnisse angezeigt. Getestet habe ich mit Firefox auf Win10 und auf Android sowie mit Chrome auf Android.

Lässt sich das Problem nachvollziehen? Die Behebung würde uns sehr weiterhelfen, da wir am Samstag ca. 200 Personen erwarten.

Vielen Dank schon jetzt für die Unterstützung!

Viele Grüße
Norbert

**Comment by timvallandi** [comment]
Hallo Norbert,

Ich kann deinen Fehler leider nicht nachstellen. 

Kannst du mir einmal folgende Infos nennen:

- Name des Vereins 
- Name des Wettkampfs 
- "Link-Alias" des Vereins (Oder den einfach den Zuschauerlink für den CheckIn) 

Dann schaue ich mal nach warum bei dir keine Anmeldungen angezeigt werden. 

Viele Grüße 
Tim

**Comment by NGoevert** [comment]
Name des Vereins: SuS Olfen
Name des Wettkampfs: Läufertag | Kaderwettkampf (22.05.2021)
Links-Alias: https://flvw.app/susolfen/rundbahn

Die Anmeldungen werden in oben beschriebener Funktion angezeigt, allerdings funktioniert (auf meinen Geräten) die Suche nicht. Sobald ich einen Buchstaben eintippe, werden keine Anmeldungen mehr angezeigt.

Viele Grüße
Norbert

**Comment by timvallandi** [comment]
Hallo Norbert,

Konnte den Fehler nun finden.
Ich Behebe diesen bis Freitag. 

Als Workaround bis dahin:
Wenn jedem Teilnehmer eine Startnummer zugewiesen wird, dann funktioniert die Suche. 

Ich habe in deinem Verein jetzt einfach mal von "01" beginnend die Anmeldungen aufsteigend mit einer Startnummer versehen und nun funktioniert auch die Suche.

Viele Grüße 
Tim

**Comment by NGoevert** [comment]
Super, vielen Dank! Mit dem Startnummern-Workaround kann ich natürlich auch leben.

Viele Grüße
Norbert

**Comment by NGoevert** [comment]
Danke für die Behebung des Problems. 

Viele Grüße
Norbert
