### ISSUE TITLE
Trainings spiel

### ISSUE THREAD

**Issue by davidstuedemann** [timvallandi/flvw-checkin#97]
Könnte man es umsetzten, dass man auch innerhalb eines Vereins Testspiele/Trainingsspiele erstellen könnte damit dort eine gemeinsame Kontaktliste entsteht, wenn z.B.  2 E-Jugend Mannschaften ein Spiel absolvieren wollen.
Bisher habe ich da leider so richtig keine möglichkeit gefunden

**Comment by timvallandi** [comment]
Heute wurde ein Update eingespielt. Trainingsspiele sind nun möglich. 

Freundschaftsspiel anlegen -> Gastteam-Link an den Trainer der anderen Mannschaft schicken -> Trainer vom "Gastteam" kann seine Mannschaft auswählen.
