### ISSUE TITLE
Unendliche Ladezeit in privatem Firefox-Fenster

### ISSUE THREAD

**Issue by NGoevert** [timvallandi/flvw-checkin#98]
Guten Tag, 

in #96 wurde ja bereits berichtet, dass ein Funktionsaufruf nicht terminierte. Ich habe jetzt ein (vergleichbares?) Problem: Wenn ich das FLVW-CheckIn in einem privaten Firefox-Fenster aufrufe, kommt der Aufruf ebenfalls nicht zu einem Ende. Die Konsole spuckt eine Fehlermeldung aus (hoffentlich in folgendem Screenshot erkennbar):

![grafik](https://user-images.githubusercontent.com/80310985/120104442-b4394d80-c154-11eb-8649-d0099b878b09.png)

Viele Grüße
Norbert

**Comment by timvallandi** [comment]
Ein vergleichbares Problem ist das nicht und es wird auch wahrscheinlich nicht möglich sein diesen Fehler zu beheben. Im privaten Modus werden wahrscheinlich gewisse Speichermöglichkeiten, die die Webapp benötigt, blockiert und daher lädt es nicht. Einfach die Webapp in einem normalen Browserfenster verwenden und dann wird es ja auch funktionieren.
