### ISSUE TITLE
Trainer in zwei Vereinen

### ISSUE THREAD

**Issue by aikido2** [timvallandi/flvw-checkin#99]
Hei,
ich bin Trainer in zwei Vereinen. Kriege ich die beide in die App? Oder brauche ich die App zweimal mit verschiedenen Usernamen?

**Comment by timvallandi** [comment]
Hi, dafür brauchst du leider 2 unterschiedliche Accounts. 
Mehrere Vereine in einem Account werden derzeit nicht unterstützt.

**Comment by aikido2** [comment]
ok. Danke für die schnelle Antwort! Kann ich dann die iPhone-App auch zweimal installieren?

**Comment by timvallandi** [comment]
Könntest Du mal ausprobieren. 
Das sollte wahrscheinlich funktionieren.

**Comment by aikido2** [comment]
War nicht nötig, ich kann beide Accounts in der iPhoneApp benutzen, muss mich nur jedes Mal ausloggen. 
Danke für die HIlfe!
